---
- name: install docker on nodes
  hosts: web
  remote_user: ubuntu
  become_method: sudo
  become_user: root
  

  tasks:
  - name: install required packages
    apt:
      name: "*"
      state: latest
    become: yes

  - name: add docker official gpg key
    apt_key: 
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    become: yes

  - name: add docker apt repo
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
    become: yes

