---
- name: Generate SSH key 
  hosts: self
  connection: local

  vars:
    ssh_key_filename: new_key_pair

  tasks:
  - name: generate an SSH keypair "{{new_key_pair}}"
    openssh_keypair:
        path: "~/{{ssh_key_filename}}"
        type: rsa
        size: 4096
        state: present
        force: no

  